force-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description>Represents either job or personal experience. Aims to allow for easy searching of jobs and personal experience for potential employers.</description>
    <label>Experience</label>
    <nameField>
        <label>Experience Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ExperienceTriggerHandler.cls
public with sharing class ExperienceTriggerHandler {
    private boolean m_isExecuting = false;
    private integer BatchSize = 0;
    public static boolean IsFromBachJob ;
    public static boolean isFromUploadAPI=false;
    
    public ExperienceTriggerHandler(boolean isExecuting, integer size)
    {
        m_isExecuting = isExecuting;
        BatchSize = size;
    }
    public void onBeforeInsert(List<Experience__c> newExperiences)
    {
        

    }
    public void onAfterInsert(List<Experience__c> newExperiences)
    {
        system.debug('Experience Trigger On After Insert');
        //Recaculate the Skills on the Job__c Object
        Set<Id> jobids = ExperienceHelper.getJobIds(newExperiences);
        ExperienceHelper.updateJobSkills(jobIds);
    }
    public void onAfterUpdate( List<Experience__c> newExperiences, List<Experience__c> oldExperiences, Map<ID, Experience__c> newExperienceMap , Map<ID, Experience__c> oldExperienceMap )
    {
        system.debug('Experience Trigger On After Update');
        //Recaculate the Skills on the Job__c Object
        Set<Id> jobids = ExperienceHelper.getJobIds(newExperiences);
        ExperienceHelper.updateJobSkills(jobIds);
        
    }
    public void onBeforeUpdate( List<Experience__c> newExperiences, List<Experience__c> oldExperiences, Map<ID, Experience__c> newExperienceMap , Map<ID, Experience__c> oldExperienceMap )
    {
        system.debug('Experience Trigger On Before Update');
    }

    @future 
    public static void onAfterUpdateAsync(Set<ID> newExperienceIDs)
    {

    }      
    public boolean isTriggerContext
    {
        get{ return m_isExecuting;}
    }
    
    public boolean isVisualforcePageContext
    {
        get{ return !IsTriggerContext;}
    }
    
    public boolean isWebServiceContext
    {
        get{ return !IsTriggerContext;}
    }
    
    public boolean isExecuteAnonymousContext
    {
        get{ return !IsTriggerContext;}
    }
}