force-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description>Represents either job or personal experience. Aims to allow for easy searching of jobs and personal experience for potential employers.</description>
    <label>Experience</label>
    <nameField>
        <label>Experience Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Job__r.Company__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>IF( ISBLANK( End_Date__c ) ,



IF(FLOOR((TODAY()- Start_Date__c)/365)&gt;0, TEXT(FLOOR((TODAY()- Start_Date__c)/365)) &amp;&apos; Years&apos; &amp; &apos; &apos;, &apos;&apos;)

&amp;


TEXT(FLOOR(MOD((TODAY()- Start_Date__c),365)/30)) &amp;&apos; Months&apos; &amp; &apos; &apos; &amp;


TEXT(MOD(MOD((TODAY()- Start_Date__c),365),30)) &amp;&apos; Days&apos;


,


IF(FLOOR((End_Date__c - Start_Date__c )/365)&gt;0, TEXT(FLOOR((End_Date__c - Start_Date__c )/365)) &amp;&apos; Years&apos; &amp; &apos; &apos;, &apos;&apos;)

&amp;


TEXT(FLOOR(MOD((End_Date__c - Start_Date__c ),365)/30)) &amp;&apos; Months&apos; &amp; &apos; &apos; &amp;


TEXT(MOD(MOD((End_Date__c - Start_Date__c ),365),30)) &amp;&apos; Days&apos;





)</formula>
    <label>Duration</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <formula>Job__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Job Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <description>List of skills used for this experience</description>
    <inlineHelpText>List skills you used for this experience</inlineHelpText>
    <label>Skills</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skills</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <formula>Company__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Current_Full_Time_Position__c.field-meta.xml
<CustomField>
    <fullName>Current_Full_Time_Position__c</fullName>
    <formula>IF( ISBLANK( End_Date__c ) , TRUE, FALSE)</formula>
    <label>Current Full Time Position</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>IF( ISBLANK( End_Date__c ) , 

 

 IF(FLOOR((TODAY()- Start_Date__c)/365)&gt;0, TEXT(FLOOR((TODAY()- Start_Date__c)/365)) &amp;&apos; Years&apos; &amp; &apos; &apos;, &apos;&apos;) 

 &amp; 
 

TEXT(FLOOR(MOD((TODAY()- Start_Date__c),365)/30)) &amp;&apos; Months&apos; &amp; &apos; &apos; &amp; 
 

TEXT(MOD(MOD((TODAY()- Start_Date__c),365),30)) &amp;&apos; Days&apos;


, 


 IF(FLOOR((End_Date__c - Start_Date__c )/365)&gt;0, TEXT(FLOOR((End_Date__c - Start_Date__c )/365)) &amp;&apos; Years&apos; &amp; &apos; &apos;, &apos;&apos;) 

 &amp; 
 

TEXT(FLOOR(MOD((End_Date__c - Start_Date__c ),365)/30)) &amp;&apos; Months&apos; &amp; &apos; &apos; &amp; 
 

TEXT(MOD(MOD((End_Date__c - Start_Date__c ),365),30)) &amp;&apos; Days&apos;





)</formula>
    <label>Duration</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Formatted_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Formatted_End_Date__c</fullName>
    <formula>CASE(MONTH(End_Date__c),1, &quot;January&quot;,2, &quot;February&quot;,3, &quot;March&quot;,4, &quot;April&quot;,5, &quot;May&quot;,6, &quot;June&quot;,7, &quot;July&quot;,8, &quot;August&quot;,9, &quot;September&quot;,10, &quot;October&quot;,11, &quot;November&quot;,12, &quot;December&quot;,&quot;None&quot;) &amp; &quot; &quot; &amp; TEXT(YEAR(End_Date__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Formatted End Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Formatted_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Formatted_Start_Date__c</fullName>
    <formula>CASE(MONTH(Start_Date__c),1, &quot;January&quot;,2, &quot;February&quot;,3, &quot;March&quot;,4, &quot;April&quot;,5, &quot;May&quot;,6, &quot;June&quot;,7, &quot;July&quot;,8, &quot;August&quot;,9, &quot;September&quot;,10, &quot;October&quot;,11, &quot;November&quot;,12, &quot;December&quot;,&quot;None&quot;) &amp; &quot; &quot; &amp; TEXT(YEAR(Start_Date__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Formatted Start Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <defaultValue>&quot;utility:case&quot;</defaultValue>
    <description>use this to control the icon displayed on the resume LWC</description>
    <label>Icon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Job_Location__c.field-meta.xml
<CustomField>
    <fullName>Job_Location__c</fullName>
    <label>Job Location</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Remote_Work__c.field-meta.xml
<CustomField>
    <fullName>Remote_Work__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Remote Work</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Skills.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>Altium</fullName>
    </customValue>
    <customValue>
        <fullName>Analog Circuit Design</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Android</fullName>
    </customValue>
    <customValue>
        <fullName>Apex</fullName>
    </customValue>
    <customValue>
        <fullName>App Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Arduino</fullName>
    </customValue>
    <customValue>
        <fullName>Art</fullName>
    </customValue>
    <customValue>
        <fullName>ASIC</fullName>
    </customValue>
    <customValue>
        <fullName>Aura</fullName>
    </customValue>
    <customValue>
        <fullName>Bandsaw</fullName>
    </customValue>
    <customValue>
        <fullName>Bash</fullName>
    </customValue>
    <customValue>
        <fullName>Batch Apex</fullName>
    </customValue>
    <customValue>
        <fullName>Bike</fullName>
    </customValue>
    <customValue>
        <fullName>BitBucket</fullName>
    </customValue>
    <customValue>
        <fullName>C++</fullName>
    </customValue>
    <customValue>
        <fullName>Cloudflare</fullName>
    </customValue>
    <customValue>
        <fullName>CNC</fullName>
    </customValue>
    <customValue>
        <fullName>CodeServer</fullName>
    </customValue>
    <customValue>
        <fullName>Commerce Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Community Builder</fullName>
    </customValue>
    <customValue>
        <fullName>Containerization</fullName>
    </customValue>
    <customValue>
        <fullName>Copado</fullName>
    </customValue>
    <customValue>
        <fullName>CPQ</fullName>
    </customValue>
    <customValue>
        <fullName>CSS</fullName>
    </customValue>
    <customValue>
        <fullName>Custom DNS</fullName>
    </customValue>
    <customValue>
        <fullName>Dell Boomi</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Circuit Design</fullName>
    </customValue>
    <customValue>
        <fullName>Docker</fullName>
    </customValue>
    <description>List of skills applicable to experiences, about me and tech demos</description>
    <masterLabel>Skills</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ResumePDFHelper.cls
public with sharing class ResumePDFHelper {
  public List<Job__c> allJobs { get; set; }
  public Map<Job__c, List<Experience__c>> allJobsMap { get; set; }
  public List<String> allSkills { get; set; }
  public List<Job__c> allJobsShort { get; set; }
  public Map<Job__c, List<Experience__c>> allJobsMapShort { get; set; }
  public List<String> allSkillsShort { get; set; }

  public ResumePDFHelper() {
    allJobs = [
      SELECT
        Id,
        Company_Name__c,
        Current_Full_Time_Position__c,
        Description__c,
        Duration__c,
        Icon__c,
        Name,
        End_Date__c,
        Skills__c,
        Start_Date__c,
        Job_Location__c,
        Remote_Work__c,
        Formatted_Start_Date__c,
        Formatted_End_Date__c,
        (
          SELECT
            Id,
            Company__c,
            Description__c,
            Duration__c,
            Job_Title__c,
            Name,
            End_Date__c,
            Job__c,
            RecordTypeId,
            Skills__c,
            Start_Date__c
          FROM Experiences__r
          ORDER BY Start_Date__c DESC
          LIMIT 5
        )
      FROM Job__c
      ORDER BY Start_Date__c DESC
    ];
    allJobsMap = new Map<Job__c, List<Experience__c>>();
    allJobsShort = new List<Job__c>();
    allJobsMapShort = new Map<Job__c, List<Experience__c>>();
    allSkillsShort = new List<String>();
    Set<String> tempAllSkills = new Set<String>();
    Set<String> tempAllSkillsShort = new Set<String>();
    Integer i = 0;

    for (Job__c job : allJobs) {
      tempAllSkills.addAll(job.Skills__c.split(';'));

      allJobsMap.put(job, job.Experiences__r);
      if (i < 3) {
        List<Experience__c> shortExps = new List<Experience__c>();
        Job__c tempjob = job;
        for (Integer j = 0; (j < 3 && j < job.Experiences__r.size()); j++) {
          shortExps.add(job.Experiences__r[j]);
          tempAllSkillsShort.addAll(job.Skills__c.split(';'));
        }
        allJobsShort.add(job);
        allJobsMapShort.put(job, shortExps);
        i++;
      }
    }
    allSkills = new List<String>(tempAllSkills);
    allSkills.sort();
    allSkillsShort = new List<String>(tempAllSkillsShort);
    allSkillsShort.sort();
  }

  @AuraEnabled
  public static Blob generateOnePagePDF() {
    PageReference pdfPage = new PageReference('/apex/ResumeOnePagePDF');
    Blob pdfBlob = pdfPage.getContentAsPDF();
    return pdfBlob;
  }
}