force-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description>Represents either job or personal experience. Aims to allow for easy searching of jobs and personal experience for potential employers.</description>
    <label>Experience</label>
    <nameField>
        <label>Experience Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <description>List of skills used for this experience</description>
    <inlineHelpText>List skills you used for this experience</inlineHelpText>
    <label>Skills</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skills</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Skills.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>Altium</fullName>
    </customValue>
    <customValue>
        <fullName>Analog Circuit Design</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Android</fullName>
    </customValue>
    <customValue>
        <fullName>Apex</fullName>
    </customValue>
    <customValue>
        <fullName>App Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Arduino</fullName>
    </customValue>
    <customValue>
        <fullName>Art</fullName>
    </customValue>
    <customValue>
        <fullName>ASIC</fullName>
    </customValue>
    <customValue>
        <fullName>Aura</fullName>
    </customValue>
    <customValue>
        <fullName>Bandsaw</fullName>
    </customValue>
    <customValue>
        <fullName>Bash</fullName>
    </customValue>
    <customValue>
        <fullName>Batch Apex</fullName>
    </customValue>
    <customValue>
        <fullName>Bike</fullName>
    </customValue>
    <customValue>
        <fullName>BitBucket</fullName>
    </customValue>
    <customValue>
        <fullName>C++</fullName>
    </customValue>
    <customValue>
        <fullName>Cloudflare</fullName>
    </customValue>
    <customValue>
        <fullName>CNC</fullName>
    </customValue>
    <customValue>
        <fullName>CodeServer</fullName>
    </customValue>
    <customValue>
        <fullName>Commerce Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Community Builder</fullName>
    </customValue>
    <customValue>
        <fullName>Containerization</fullName>
    </customValue>
    <customValue>
        <fullName>Copado</fullName>
    </customValue>
    <customValue>
        <fullName>CPQ</fullName>
    </customValue>
    <customValue>
        <fullName>CSS</fullName>
    </customValue>
    <customValue>
        <fullName>Custom DNS</fullName>
    </customValue>
    <customValue>
        <fullName>Dell Boomi</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Circuit Design</fullName>
    </customValue>
    <customValue>
        <fullName>Docker</fullName>
    </customValue>
    <description>List of skills applicable to experiences, about me and tech demos</description>
    <masterLabel>Skills</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ExperienceHelper.cls
public with sharing class ExperienceHelper {


    public static Set<Id> getJobIds(List<Experience__c> exps){
        Set<Id> jobIds = new Set<Id>();

        for(Experience__c exp :exps){
            jobIds.add(exp.Job__c);
        }
        return jobIds;

    }

    public static void updateJobSkills(Set<Id> jobIds){
        List<Job__c> jobs = [SELECT Id, Skills__c, (SELECT ID, Skills__c FROM Experiences__r) FROM Job__c WHERE Id IN :jobIds WITH SECURITY_ENFORCED];

        for(Job__c job :jobs){
            Set<String> tempskills = new Set<String>();

            for(Experience__c exp :job.Experiences__r){
                tempskills.addAll(exp.Skills__c.split(';'));
            }
            job.Skills__c = String.join(tempSkills, ';');
        }
            update jobs;

    }
  


}